### ISSUE TITLE
Not able to run locally

### ISSUE THREAD

**Issue by HE-MG** [old-school-kid/Warehouse-management#8]
I downloaded the saved modules and followed the rest of the instructions in the Readme. I get the below error

`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements'`

**Comment by old-school-kid** [comment]
Hi @HE-MG 
The command should be `pip install -r requiremnets.txt` instead of `pip install -r requirements`. I have made the necessary change.

**Comment by HE-MG** [comment]
Changed it to `pip install -r requirements.txt` 

Thank you
